using System;
using System.Collections.Generic;
using ReFolder.Dir.Description;

namespace ReFolder.Dir
{
    [Serializable]
    public class ChildDir : MainDir, IEditableDirWithChildrenAndParrent
    {
        public IEditableDirWithChildren ParrentDir { get; set; }
      

        public ChildDir(IMutableSystemObjectDescription description, IEditableDirWithChildren mainDir,  List<IEditableDirWithChildrenAndParrent> children) : base( description, children)
        {
            this.ParrentDir = mainDir;
        }
        public ChildDir(IMutableSystemObjectDescription description, IEditableDirWithChildren mainDir) : base(description)
        {
            this.ParrentDir = mainDir;
        }
        public ChildDir(string Name, IEditableDirWithChildren mainDir)
        {
            this.ParrentDir = mainDir;
            DirDescription dirDescription = new DirDescription(
                name: Name,
                fullName: $"{mainDir.Description.FullName}\\{Name}"
                );

            Description = dirDescription;

        }
        public string AutoGenerateDirFullName()
        {
            if (ParrentDir.Description.FullName == null) throw new NullReferenceException();
            string fullName = $"{ParrentDir.Description.FullName}\\{Description.Name}";
            Description.FullName = fullName;
            return fullName;
        }

    }
}
