using NUnit.Framework;
using Moq;
using ReFolder.Dir;
using ReFolder.Dir.Description;
using System;
using System.Collections.Generic;


namespace ReFolder.Tests
{
    class ChildDir_Tests
    {
        [Test]
        public void AutoGenerateDirFullName_Pass_WhenAcceptableParentIsDelivered()
        {
            //arrange
            string mainAddress = "c:\\blueCat\\MyCats";
            string childDirName = "puszek";
            IEditableDirWithChildren main = Mock.Of<IEditableDirWithChildren>(x=> 
            x.Description.FullName==mainAddress);
            IEditableDirWithChildrenAndParent childDir = new ChildDir(childDirName, main);
            //act
            var address = childDir.AutoGenerateDirFullName();
            //assert
            Assert.AreEqual($"{mainAddress}\\puszek", address);
        }
        [Test]
        public void AutoGenerateDirFullName_ChangeDirFullName_WhenWhenParentFullNameChange()
        {
            //arange
            string fullName = "c:\\cats\\RedCats";
            string childDirName = "puszek";
            IEditableDirWithChildren mainDir = new MainDir(new DirDescription("c:\\cats\\BlueCats", "BlueCats"));
            IEditableDirWithChildrenAndParent childDir = new ChildDir(childDirName, mainDir);
            mainDir.AddChildToChildrenList(childDir);
            mainDir.Description.FullName = fullName;
            //act
            childDir.AutoGenerateDirFullName();
            //assert
            Assert.AreEqual($"{fullName}\\{childDirName}",childDir.Description.FullName);
        }
        [Test]
        public void AutoGenerateDirFullName_ThrowNullReferenceException_WhenParentFullNameIsNull()
        {
            //arange
            IEditableDirWithChildren mainDir = Mock.Of<IEditableDirWithChildren>(x =>
             x.Description.FullName == null);
            IEditableDirWithChildrenAndParent childDir = new ChildDir("puszek", mainDir);
            mainDir.AddChildToChildrenList(childDir);
            //act
            TestDelegate action=() => childDir.AutoGenerateDirFullName();
            //assert
            Assert.Throws<NullReferenceException>(action);
        }
    }
}
